grafana:
  nodeSelector:
    kubernetes.io/os: linux
    role: backend

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      folder: /tmp/dashboards
      provider: 
        allowUiUpdates: true
        foldersFromFilesStructure: true

      annotations: 
        k8s-sidecar-target-directory: "/tmp/dashboards/kubernetes"

prometheus:
  prometheusSpec:
    scrapeInterval: '15s' # for spike test (~ 1m)
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    
    nodeSelector:
      kubernetes.io/os: linux
      role: backend
      
    enableRemoteWriteReceiver: true
    enableFeatures: 
      - native-histograms

    # storageSpec:
    #  volumeClaimTemplate:
    #    spec:
    #      storageClassName: gp3
    #      accessModes: ["ReadWriteOnce"]
    #      resources:
    #        requests:
    #          storage: 2Gi

    additionalScrapeConfigs:
      - job_name: "mysql-exporter"
        static_configs:
          - targets: ["mysql-exporter-prometheus-mysql-exporter:9104"]

      - job_name: "spring-actuator"
        # static_configs:
        #   - targets: ["development-ticketing-application.default:8080"]
        metrics_path: "/actuator/prometheus"
        kubernetes_sd_configs:
          - role: pod
            selectors:
              - role: "pod"
                label: "app.kubernetes.io/name=ticketing-application"

      - job_name: "nginx-controller"
        metrics_path: "/metrics"
        static_configs:
          - targets: ["development-ingress-nginx-controller-metrics.default:10254"]

prometheusOperator:
  nodeSelector:
    kubernetes.io/os: linux
    role: backend

alertmanager:
  enabled: false
  nodeSelector:
    kubernetes.io/os: linux
    role: backend

kubeStateMetrics:
  nodeSelector:
    kubernetes.io/os: linux
    role: backend
