apiVersion: v1
kind: Service
metadata:
  name: prometheus-grafana-node-port
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: grafana