{
 "title": "1 Kubernetes All-in-one Cluster Monitoring KR",
 "description": "This dashboard is one of major topic for Kubernetes Book and best optimized for virtual machine environment provided with https://github.com/sysnet4admin/_Book_k8sInfraNotice: It may be running on the other environment but cannot be guaranteed.",
 "tags": [
  "kubernetes",
  "k8s"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_status_condition,node)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_uname_info{nodename=\"$node\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "클러스터 요약",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "마스터 정상 가동률",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(\navg_over_time((sum without ()(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\".*.dashboard.*|.*.dns.*|kube.*|.*.calico.*|.*.flannel.*|.*.etcd.*\"}) \n/ \ncount without ()(kube_pod_container_status_ready{namespace=\"kube-system\",pod=~\".*.dashboard.*|.*.dns.*|kube.*|.*.calico.*|.*.flannel.*|.*.etcd.*\"}))[$__interval:5m])\n)"
    }
   ]
  },
  {
   "title": "노드 현황",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 1 },
   "targets": [
    { "expr": "kube_node_info", "legendFormat": "{{node}}" },
    {
     "expr": " (count by (node)(container_spec_memory_reservation_limit_bytes{pod!=\"\"}))"
    },
    {
     "expr": "max\n  by(node) (max by(instance) (kubelet_running_pod_count{job=\"kubelet\",metrics_path=\"/metrics\"})\n  * on(instance) group_left(node) kubelet_node_name{job=\"kubelet\",metrics_path=\"/metrics\"})\n"
    },
    {
     "expr": "sum by (node)(label_replace(instance:node_cpu:ratio + on(instance) group_left(nodename) \nnode_uname_info,\"node\",\"$1\",\"nodename\", \"(.+)\") ) / sum by (node)(kube_node_status_capacity{resource=\"cpu\"})"
    },
    { "expr": "kube_node_role" },
    {
     "expr": "label_replace(up{job=\"kubernetes-nodes\"}, \"node\", \"$1\", \"instance\", \"(.+)\")"
    },
    {
     "expr": "label_replace(avg by (kubernetes_node) (time() - node_boot_time_seconds), \"node\", \"$1\", \"kubernetes_node\", \"(.+)\")"
    }
   ]
  },
  {
   "title": "네임스페이스",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": " count(kube_namespace_created)", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": " count(count by (pod)(kube_pod_container_info{pod!=\"\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "PVC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_info) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "전체 클러스터",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "노드별 CPU 점유율",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum by (instance,nodename) (irate(node_cpu_seconds_total{mode!~\"guest.*|idle|iowait\"}[$__rate_interval])) + on(instance) group_left(nodename) \nnode_uname_info) - 1",
     "legendFormat": "{{nodename}} "
    }
   ]
  },
  {
   "title": "노드별 메모리 사용량",
   "type": "graph",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes  + on(instance) group_left(nodename) \nnode_uname_info) - (node_memory_MemAvailable_bytes  + on(instance) group_left(nodename) \nnode_uname_info))",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "초당 네트워크 트래픽",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes", "label": "수신 | 송신" }
   ],
   "targets": [
    {
     "expr": "sum (rate(node_network_receive_bytes_total[$__rate_interval]))",
     "legendFormat": "{{kubernetes_node}}(in)"
    },
    {
     "expr": "sum (rate(node_network_transmit_bytes_total[$__rate_interval]))",
     "legendFormat": "{{kubernetes_node}}(out)"
    }
   ]
  },
  {
   "title": "API 서버 호출",
   "type": "graph",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (verb) (rate(apiserver_request_total[$__rate_interval]))",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "노드 $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU 점유율",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{mode!~\"guest.*|idle|iowait\", instance=\"$instance\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "메모리 점유율",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"$instance\"}-node_memory_MemAvailable_bytes{instance=\"$instance\"})/node_memory_MemTotal_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "디스크 사용률(%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{instance=\"$instance\"} - node_filesystem_avail_bytes{instance=\"$instance\"}) by (kubernetes_node) / sum(node_filesystem_size_bytes{instance=\"$instance\"}) by (kubernetes_node)"
    }
   ]
  },
  {
   "title": "CPU 코어",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_cpu_cores{node=\"$node\"}"
    }
   ]
  },
  {
   "title": "File descriptor / Context switches",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "used filefd" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$instance\"}",
     "legendFormat": "used filefd"
    },
    {
     "expr": "rate(node_context_switches_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "switches"
    }
   ]
  },
  {
   "title": "Disk IOPS 완료",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 29 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{device}}_Reads"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{device}}_Writes"
    },
    {
     "expr": "node_disk_io_now{instance=~\"$instance\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "메모리",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "machine_memory_bytes{node=\"$node\"}"
    }
   ]
  }
 ]
}