apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: development
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: https://github.com/f-lab-clone/ticketing-infra.git
    targetRevision: feat/74-disable-cloudwatch
    path: src/kubernetes/ticketing-chart
  
  destination:
    server: https://kubernetes.default.svc
  
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true   
    syncOptions:
      - CreateNamespace=true
