grafana:
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      folder: /tmp/dashboards
      provider: 
        allowUiUpdates: true
        foldersFromFilesStructure: true

      ## Annotations for Grafana dashboard configmaps
      annotations: 
        k8s-sidecar-target-directory: "/tmp/dashboards/kubernetes"