namespace: default

backend:
  serviceAccountName: "ticketing-backend-account"
  image:
    repository: 213060417361.dkr.ecr.ap-northeast-2.amazonaws.com/ticketing-backend-ecr
    pullPolicy: Always
    tag: "latest"

  port: 8080

  autoscaling:
    enabled: true
    replicaCount: 1
