namespace: default


backend:
  environment: dev
  serviceAccountName: "ticketing-backend-account"
  image:
    repository: 213060417361.dkr.ecr.ap-northeast-2.amazonaws.com/ticketing-backend-ecr
    pullPolicy: Always
    tag: "latest"

  port: 8080

  autoscaling:
    enabled: true
    replicaCount: 2


redis:
  image: redis:latest
  port: 6379


queuing_system:
  URL: http://development-ticketing-application-queuing-api.default.svc.cluster.local:8000/ticket

  image:
    repository: 213060417361.dkr.ecr.ap-northeast-2.amazonaws.com/ticketing-queuing-ecr
    pullPolicy: Always
    tag: "latest"

  config:
    NODE_ENV: development
    PORT: 8000
    REDIS_HOST: ticketing-redis.default.svc.cluster.local
    REDIS_PORT: 6379
    JOB_INTEVAL_SEC: 10
    JOB_MOVE_PER_INTEVAL: 20
    JOB_TICKET_EXPIRED_SEC: 180