apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ticketing-chart.fullname" . }}
  labels:
    {{- include "ticketing-chart.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  {{- if .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.backend.autoscaling.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ticketing-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ticketing-chart.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.backend.serviceAccountName }}

      nodeSelector:
        role: backend

      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ include "ticketing-chart.fullname" . }}

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"

          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"

          
          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: {{ .Values.backend.port }}
              protocol: TCP

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.backend.environment }}"
            - name: PORT
              value: "{{ .Values.backend.port }}"
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "ticketing-chart.fullname" . }}
                  key: MYSQL_USERNAME
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ticketing-chart.fullname" . }}
                  key: MYSQL_PASSWORD
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "ticketing-chart.fullname" . }}
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "ticketing-chart.fullname" . }}
                  key: MYSQL_PORT
            - name: MYSQL_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: {{ include "ticketing-chart.fullname" . }}
                  key: MYSQL_SCHEMA
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "ticketing-chart.fullname" . }}
                  key: JWT_SECRET
            - name: JWT_ISSUER
              valueFrom:
                secretKeyRef:
                  name: {{ include "ticketing-chart.fullname" . }}
                  key: JWT_ISSUER
            - name: JWT_EXPIRATION_HOURS
              valueFrom:
                secretKeyRef:
                  name: {{ include "ticketing-chart.fullname" . }}
                  key: JWT_EXPIRATION_HOURS

          volumeMounts: 
          - name: secrets-store-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true

          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http