apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-remote-write
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /api/v1/write
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: remote-write-basic-auth
spec:
  rules:
  - http:
      paths:
      - path: /api/v1/write
        pathType: Exact
        backend:
          service:
            name: prometheus-kube-prometheus-prometheus
            port:
              number: 9090
  ingressClassName: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ticketing-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /events
        pathType: Prefix
        backend:
          service:
            name: {{ include "ticketing-chart.fullname" . }}
            port:
              number: {{ .Values.backend.port }}
      - path: /reservations
        pathType: Prefix
        backend:
          service:
            name: {{ include "ticketing-chart.fullname" . }}
            port:
              number: {{ .Values.backend.port }}
      - path: /users
        pathType: Prefix
        backend:
          service:
            name: {{ include "ticketing-chart.fullname" . }}
            port:
              number: {{ .Values.backend.port }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "ticketing-chart.fullname" . }}
            port:
              number: {{ .Values.backend.port }}
  ingressClassName: nginx