apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ticketing-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /api/v1/write
        pathType: Exact
        backend:
          service:
            name: headless-to-kube-prometheus-prometheus
            port:
              number: {{ .Values.backend.port }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "ticketing-chart.fullname" . }}
            port:
              number: {{ .Values.backend.port }}
  ingressClassName: nginx