apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-chart-redis
spec:
  template:
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          command:
            - redis-server
          env:
            - name: MASTER
              value: "true"
          ports:
            - name: redis
              containerPort: {{ .Values.redis.port }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}