apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-redis
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ticketing-redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ticketing-redis
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          command:
            - redis-server
          env:
            - name: MASTER
              value: "true"
          ports:
            - name: redis
              containerPort: {{ .Values.redis.port }}