apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ include "ticketing-chart.fullname" . }}
spec:
  provider: aws
  secretObjects:
  - secretName: ticketing-secret
    type: Opaque
    data:
    - key: "MYSQL_PASSWORD"
      objectName: "MYSQL_PASSWORD"
    - key: "MYSQL_USERNAME"
      objectName: "MYSQL_USERNAME"
    - key: "MYSQL_HOST"
      objectName: "MYSQL_HOST"
    - key: "MYSQL_PORT"
      objectName: "MYSQL_PORT"
    - key: "MYSQL_SCHEMA"
      objectName: "MYSQL_SCHEMA"
    - key: "JWT_SECRET"
      objectName: "JWT_SECRET"
    - key: "JWT_EXPIRATION_HOURS"
      objectName: "JWT_EXPIRATION_HOURS"
    - key: "JWT_ISSUER"
      objectName: "JWT_ISSUER"
  parameters:
    objects: |
        - objectName: {{ include "ticketing-chart.fullname" . }}
          objectType: "secretsmanager"
          jmesPath:
            - path: "MYSQL_PASSWORD"
              objectAlias: "MYSQL_PASSWORD"
            - path: "MYSQL_USERNAME"
              objectAlias: "MYSQL_USERNAME"
            - path: "MYSQL_HOST"
              objectAlias: "MYSQL_HOST"
            - path: "MYSQL_PORT"
              objectAlias: "MYSQL_PORT"
            - path: "MYSQL_SCHEMA"
              objectAlias: "MYSQL_SCHEMA"
            - path: "JWT_SECRET"
              objectAlias: "JWT_SECRET"
            - path: "JWT_EXPIRATION_HOURS"
              objectAlias: "JWT_EXPIRATION_HOURS"
            - path: "JWT_ISSUER"
              objectAlias: "JWT_ISSUER"
