apiVersion: v1
kind: Service
metadata:
  name: {{ include "ticketing-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.backend.port }}
    targetPort: {{ .Values.backend.port }}
  selector:
    {{- include "ticketing-chart.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-grafana-node-port
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: grafana
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  name: headless-to-kube-prometheus-prometheus
  namespace: default
spec:
  clusterIP: None
  externalName: prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-kube-prometheus-prometheus-node-port
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30010
    targetPort: 9090
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: prometheus
    operator.prometheus.io/name: prometheus-kube-prometheus-prometheus
