apiVersion: v1
kind: Service
metadata:
  name: {{ include "ticketing-chart.fullname" . }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.backend.port }}
    targetPort: {{ .Values.backend.port }}
  selector:
    {{- include "ticketing-chart.selectorLabels" . | nindent 4 }}