apiVersion: v1
kind: Service
metadata:
  name: {{ include "ticketing-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.backend.port }}
    targetPort: {{ .Values.backend.port }}
  selector:
    {{- include "ticketing-chart.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ticketing-chart.fullname" . }}-queuing-api
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - port:  {{ .Values.queuing_system.config.PORT }}
    targetPort:  {{ .Values.queuing_system.config.PORT }}
  selector:
    {{- include "ticketing-chart.queuingAPISelectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-grafana-node-port
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: grafana
---
apiVersion: v1
kind: Service
metadata:
  name: morgo-argocd-server-node-port
  namespace: argocd
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/instance: morgo
    app.kubernetes.io/name: argocd-server